// Package quarantine emits skip lists in the formats test runners actually
// accept.
//
// Emitting a generic list nobody's runner can consume is the common failure
// mode here: it leaves the user to write the glue, which is exactly the work
// they wanted done. Each emitter targets a real mechanism of the framework,
// and where a framework cannot skip an individual test the output says so
// rather than pretending otherwise.
package quarantine

import (
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/rowhitswami/flakestat/internal/score"
)

// Format identifies a target test runner.
type Format string

const (
	FormatPytest Format = "pytest"
	FormatGo     Format = "go"
	FormatJest   Format = "jest"
	FormatYAML   Format = "yaml"
	FormatJSON   Format = "json"
)

// Formats lists every supported emitter.
func Formats() []string {
	return []string{
		string(FormatPytest), string(FormatGo), string(FormatJest),
		string(FormatYAML), string(FormatJSON),
	}
}

// ParseFormat validates a format name.
func ParseFormat(s string) (Format, error) {
	switch Format(strings.ToLower(strings.TrimSpace(s))) {
	case FormatPytest:
		return FormatPytest, nil
	case FormatGo:
		return FormatGo, nil
	case FormatJest:
		return FormatJest, nil
	case FormatYAML:
		return FormatYAML, nil
	case FormatJSON:
		return FormatJSON, nil
	default:
		return "", fmt.Errorf("unknown format %q (want one of: %s)", s, strings.Join(Formats(), ", "))
	}
}

// Options controls selection and rendering.
type Options struct {
	Format Format

	// IncludeBroken adds consistently-failing tests. Off by default: those are
	// broken rather than flaky, and silently skipping them hides a real defect.
	IncludeBroken bool
}

// Select picks the tests to quarantine, worst first.
func Select(results []score.Result, opts Options) []score.Result {
	out := make([]score.Result, 0, len(results))
	for _, r := range results {
		switch r.Verdict {
		case score.ClassFlaky:
			out = append(out, r)
		case score.ClassConsistentlyFail:
			if opts.IncludeBroken {
				out = append(out, r)
			}
		}
	}

	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Score != out[j].Score {
			return out[i].Score > out[j].Score
		}
		return out[i].DisplayName() < out[j].DisplayName()
	})
	return out
}

// Render writes the skip list for the configured format.
func Render(w io.Writer, results []score.Result, opts Options) error {
	selected := Select(results, opts)

	switch opts.Format {
	case FormatPytest:
		return renderPytest(w, selected)
	case FormatGo:
		return renderGo(w, selected)
	case FormatJest:
		return renderJest(w, selected)
	case FormatYAML:
		return renderYAML(w, selected)
	case FormatJSON:
		return renderJSON(w, selected)
	default:
		return fmt.Errorf("unknown format %q", opts.Format)
	}
}

// --- pytest -----------------------------------------------------------------

// PytestNodeID reconstructs a pytest node ID such as
// "tests/test_auth.py::TestAuth::test_login[oauth]".
//
// pytest reports classname as a dotted path that merges the module with any
// enclosing class ("tests.test_auth.TestAuth"), and the two cannot be
// separated reliably. The convention that class names are capitalised and
// module names are not is what pytest's own reporting relies on, so it is used
// here too. A file path from the framework always wins over this guess.
func PytestNodeID(r score.Result) string {
	var path string
	var classes []string

	if r.File != "" {
		path = r.File
		// With a known file, every capitalised segment is an enclosing class.
		for _, p := range strings.Split(r.Class, ".") {
			if isClassName(p) {
				classes = append(classes, p)
			}
		}
	} else {
		var modules []string
		for _, p := range strings.Split(r.Class, ".") {
			if p == "" {
				continue
			}
			// Once a class is seen, everything after it is also a class.
			if len(classes) > 0 || isClassName(p) {
				classes = append(classes, p)
			} else {
				modules = append(modules, p)
			}
		}
		if len(modules) > 0 {
			path = strings.Join(modules, "/") + ".py"
		}
	}

	parts := make([]string, 0, len(classes)+2)
	if path != "" {
		parts = append(parts, path)
	}
	parts = append(parts, classes...)
	parts = append(parts, r.Name)
	return strings.Join(parts, "::")
}

func isClassName(s string) bool {
	return s != "" && unicode.IsUpper(rune(s[0]))
}

func renderPytest(w io.Writer, results []score.Result) error {
	fmt.Fprintln(w, "# Generated by flakestat. Quarantined tests, worst first.")
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Use with:")
	fmt.Fprintln(w, "#   pytest $(grep -v '^#' quarantine.txt | sed 's/^/--deselect /')")

	if len(results) == 0 {
		fmt.Fprintln(w, "#\n# (nothing quarantined)")
		return nil
	}

	for _, r := range results {
		fmt.Fprintf(w, "%s\n", PytestNodeID(r))
	}
	return nil
}

// --- go ---------------------------------------------------------------------

func renderGo(w io.Writer, results []score.Result) error {
	fmt.Fprintln(w, "# Generated by flakestat. Pass to go test -skip:")

	if len(results) == 0 {
		fmt.Fprintln(w, "#\n# (nothing quarantined)")
		return nil
	}

	names := make([]string, 0, len(results))
	for _, r := range results {
		// Subtests arrive as "TestOuter/sub_case"; -skip matches the full path,
		// so quoting the whole name is both correct and precise.
		names = append(names, regexp.QuoteMeta(r.Name))
	}

	fmt.Fprintf(w, "#   go test -skip \"$(grep -v '^#' quarantine.txt)\" ./...\n")
	fmt.Fprintf(w, "^(%s)$\n", strings.Join(names, "|"))
	return nil
}

// --- jest -------------------------------------------------------------------

func renderJest(w io.Writer, results []score.Result) error {
	// jest can only ignore whole files from configuration: --testNamePattern is
	// positive-only, and there is no per-test deselect. Skipping a file also
	// skips the healthy tests in it, so that trade-off is stated up front
	// rather than discovered later.
	fmt.Fprintln(w, "// Generated by flakestat.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// NOTE: jest cannot skip individual tests from config, only whole files.")
	fmt.Fprintln(w, "// Every listed file below contains at least one quarantined test, and")
	fmt.Fprintln(w, "// ignoring it will also skip the healthy tests in that file.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// Merge into jest.config.js, or use --testPathIgnorePatterns.")

	files := map[string][]string{}
	var order []string
	for _, r := range results {
		f := r.File
		if f == "" {
			f = r.Suite
		}
		if f == "" {
			continue
		}
		if _, seen := files[f]; !seen {
			order = append(order, f)
		}
		files[f] = append(files[f], r.Name)
	}

	patterns := make([]string, 0, len(order))
	for _, f := range order {
		patterns = append(patterns, "^"+regexp.QuoteMeta(f)+"$")
	}

	out := map[string][]string{"testPathIgnorePatterns": patterns}
	blob, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}

	for _, f := range order {
		fmt.Fprintf(w, "// %s: %s\n", f, strings.Join(files[f], ", "))
	}
	_, err = fmt.Fprintf(w, "%s\n", blob)
	return err
}

// --- generic ----------------------------------------------------------------

type entry struct {
	TestID  string  `json:"test_id"`
	Test    string  `json:"test"`
	Name    string  `json:"name"`
	Suite   string  `json:"suite,omitempty"`
	Class   string  `json:"class,omitempty"`
	File    string  `json:"file,omitempty"`
	Verdict string  `json:"verdict"`
	Score   float64 `json:"score"`
	Runs    int     `json:"runs"`
	Passes  int     `json:"passes"`
	Fails   int     `json:"fails"`
}

func entries(results []score.Result) []entry {
	out := make([]entry, 0, len(results))
	for _, r := range results {
		out = append(out, entry{
			TestID:  r.TestID,
			Test:    r.DisplayName(),
			Name:    r.Name,
			Suite:   r.Suite,
			Class:   r.Class,
			File:    r.File,
			Verdict: string(r.Verdict),
			Score:   r.Score,
			Runs:    r.Runs,
			Passes:  r.Passes,
			Fails:   r.Fails,
		})
	}
	return out
}

func renderJSON(w io.Writer, results []score.Result) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(struct {
		Version     int     `json:"version"`
		Quarantined []entry `json:"quarantined"`
	}{Version: 1, Quarantined: entries(results)})
}

// renderYAML writes YAML by hand rather than taking on a dependency: the shape
// is fixed and shallow, and the binary is otherwise dependency-free.
func renderYAML(w io.Writer, results []score.Result) error {
	fmt.Fprintln(w, "# Generated by flakestat.")
	fmt.Fprintln(w, "version: 1")
	fmt.Fprintln(w, "quarantined:")

	if len(results) == 0 {
		fmt.Fprintln(w, "  []")
		return nil
	}

	for _, e := range entries(results) {
		fmt.Fprintf(w, "  - test_id: %s\n", e.TestID)
		fmt.Fprintf(w, "    test: %s\n", yamlString(e.Test))
		fmt.Fprintf(w, "    name: %s\n", yamlString(e.Name))
		if e.File != "" {
			fmt.Fprintf(w, "    file: %s\n", yamlString(e.File))
		}
		fmt.Fprintf(w, "    verdict: %s\n", e.Verdict)
		fmt.Fprintf(w, "    score: %.4f\n", e.Score)
		fmt.Fprintf(w, "    runs: %d\n", e.Runs)
		fmt.Fprintf(w, "    passes: %d\n", e.Passes)
		fmt.Fprintf(w, "    fails: %d\n", e.Fails)
	}
	return nil
}

// yamlString always double-quotes, which is valid for every scalar and avoids
// the "Norway problem" and colon-in-value ambiguities entirely.
func yamlString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\t':
			b.WriteString("\\t")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
